# Generated by Django 5.2.6 on 2025-09-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('photographer', 'Photographer')], default='client', max_length=20),
        ),
    ]
